import type { Vehicle } from "@/lib/types";

const photos = [
  "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1400&q=85",
  "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1400&q=85",
  "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1400&q=85",
  "https://images.unsplash.com/photo-1504215680853-026ed2a45def?auto=format&fit=crop&w=1400&q=85",
  "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1400&q=85",
  "https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=1400&q=85",
];

const gallery = (offset: number) =>
  Array.from({ length: 5 }, (_, index) => photos[(offset + index) % photos.length]);

export function getDemoVehicles(): Vehicle[] {
  const now = Date.now();
  const after = (minutes: number) => new Date(now + minutes * 60_000).toISOString();
  const before = (minutes: number) => new Date(now - minutes * 60_000).toISOString();

  return [
    {
      id: "demo-camaro-2021",
      ownerUid: "seller-lucas",
      title: "2021 Chevrolet Camaro LT",
      year: 2021,
      articleType: "Automóvil",
      brand: "Chevrolet",
      model: "Camaro LT",
      engine: "2.0L Turbo",
      transmission: "Automática",
      fuel: "Gasolina",
      drivetrain: "RWD",
      cylinders: 4,
      damage: "Verde",
      photos: gallery(0),
      basePrice: 92_000,
      currentBid: 123_000,
      bidCount: 18,
      startsAt: before(80),
      endsAt: after(42),
      status: "ACTIVE",
    },
    {
      id: "demo-rav4-2020",
      ownerUid: "seller-andrea",
      title: "2020 Toyota RAV4 XLE",
      year: 2020,
      articleType: "SUV",
      brand: "Toyota",
      model: "RAV4 XLE",
      engine: "2.5L",
      transmission: "Automática",
      fuel: "Gasolina",
      drivetrain: "AWD",
      cylinders: 4,
      damage: "Amarillo",
      photos: gallery(1),
      basePrice: 78_000,
      currentBid: 86_000,
      bidCount: 9,
      startsAt: before(140),
      endsAt: after(97),
      status: "ACTIVE",
    },
    {
      id: "demo-f150-2019",
      ownerUid: "seller-pablo",
      title: "2019 Ford F-150 XLT",
      year: 2019,
      articleType: "Pickup",
      brand: "Ford",
      model: "F-150 XLT",
      engine: "3.5L EcoBoost",
      transmission: "Automática",
      fuel: "Gasolina",
      drivetrain: "4WD",
      cylinders: 6,
      damage: "Rojo",
      photos: gallery(2),
      basePrice: 56_000,
      currentBid: 56_000,
      bidCount: 1,
      startsAt: before(23),
      endsAt: after(133),
      status: "ACTIVE",
    },
    {
      id: "demo-civic-2022",
      ownerUid: "seller-lucas",
      title: "2022 Honda Civic Sport",
      year: 2022,
      articleType: "Automóvil",
      brand: "Honda",
      model: "Civic Sport",
      engine: "2.0L",
      transmission: "CVT",
      fuel: "Gasolina",
      drivetrain: "FWD",
      cylinders: 4,
      damage: "Verde",
      photos: gallery(3),
      basePrice: 80_000,
      currentBid: 0,
      bidCount: 0,
      startsAt: before(12),
      endsAt: after(201),
      status: "ACTIVE",
    },
    {
      id: "demo-tucson-2021",
      ownerUid: "seller-andrea",
      title: "2021 Hyundai Tucson GLS",
      year: 2021,
      articleType: "SUV",
      brand: "Hyundai",
      model: "Tucson GLS",
      engine: "2.0L",
      transmission: "Automática",
      fuel: "Gasolina",
      drivetrain: "FWD",
      cylinders: 4,
      damage: "Amarillo",
      photos: gallery(4),
      basePrice: 63_000,
      currentBid: 73_000,
      bidCount: 11,
      startsAt: before(71),
      endsAt: after(63),
      status: "ACTIVE",
    },
    {
      id: "demo-mustang-2018",
      ownerUid: "seller-pablo",
      title: "2018 Ford Mustang EcoBoost",
      year: 2018,
      articleType: "Automóvil",
      brand: "Ford",
      model: "Mustang EcoBoost",
      engine: "2.3L Turbo",
      transmission: "Manual",
      fuel: "Gasolina",
      drivetrain: "RWD",
      cylinders: 4,
      damage: "Rojo",
      photos: gallery(5),
      basePrice: 49_000,
      currentBid: 64_000,
      bidCount: 16,
      startsAt: before(90),
      endsAt: after(18),
      status: "ACTIVE",
    },
  ];
}
